/**
 * Generated Type Definitions for Demo
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface IDemo {
  id: string;
  created_at: string;
  updated_at: string;
  full_name: string;
  email: string;
  website?: string | null;
  phone?: string | null;
  keywords?: string | null;
  secret_code?: string | null;
  age: number;
  salary?: number | null;
  experience_level?: number | null;
  satisfaction?: number | null;
  birth_date?: string | null;
  appointment_time?: string | null;
  event_datetime?: string | null;
  target_month?: string | null;
  target_week?: string | null;
  language: 'en' | 'es' | 'fr' | 'de' | 'ja';
  skill_level: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  newsletter_subscription?: boolean;
  notifications_enabled?: boolean;
  favorite_color?: string | null;
  profile_picture?: string | null;
  resume_file?: string | null;
  biography?: string | null;
  config_json?: object | null;
  skills?: string | null;
  user_id?: string | null;
  metadata?: object | null;
}

export type TDemoFormData = Omit<Demo, 'id' | 'created_at' | 'updated_at'>;
export type TUpdateDemoData = Partial<DemoFormData>;
