/**
 * Generated Type Definitions for Books
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface Books {
  id: string;
  created_at: string;
  updated_at: string;
  isbn?: string | null;
  title: string;
  author: string;
  genre: string;
  date_read?: string | null;
  date_published?: string | null;
  notes?: string | null;
  rating?: number | null;
  progress?: number | null;
  read?: boolean;
}

export type BooksFormData = Omit<Books, 'id' | 'created_at' | 'updated_at'>;
export type UpdateBooksData = Partial<BooksFormData>;
