/**
 * Generated Type Definitions for FinalQualityForm
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface IFinalQualityForm {
  id: string;
  created_at: string;
  updated_at: string;
  inspector_name: string;
  equipment_type: string;
  serial_number: 'not-configured';
  support_case: 'not-configured';
  customer: 'not-configured';
  maintenance_date: string;
  next_maintenance_date: string;
  address: string;
  customer_contact_name: string;
  customer_contact_email: string;
  confirm_system_performance?: boolean;
  pre_service_ablation_performance: 'excellent' | 'good' | 'fair' | 'poor' | 'error';
  pre_service_pulsing_power: number;
  pre_service_cw_power: number;
  replace_desiccant_packs?: boolean;
  confirm_humidity_settings?: boolean;
  capture_laser_settings?: boolean;
  copy_logfiles?: boolean;
  inspect_protection_window?: boolean;
  clean_replace_optics?: boolean;
  annual_water_service?: boolean;
  confirm_o_rings_screws?: boolean;
  tape_resonator_seams?: boolean;
  inspect_protection_hose?: boolean;
  update_mds_sensor?: boolean;
  clean_equipment_dust?: boolean;
  verify_air_pressure?: boolean;
  verify_interlocks_estops?: boolean;
  issues_found?: string | null;
  corrective_actions?: string | null;
  recommendations?: string | null;
  parts_used?: object | null;
  job_hours?: object | null;
  maintenance_pictures?: string | null;
  supporting_documents?: string | null;
  technician_signature: string;
  customer_signature?: string | null;
}

export type TFinalQualityFormFormData = Omit<FinalQualityForm, 'id' | 'created_at' | 'updated_at'>;
export type TUpdateFinalQualityFormData = Partial<FinalQualityFormFormData>;
