/**
 * Generated Type Definitions Index
 * 
 * This file is automatically generated from all FormConfiguration files.
 * Do not edit manually - regenerate using: npm run generate:all
 * 
 * Generated from 5 configuration(s):
 * - finalQualityFormConfiguration.ts (finalQualityFormConfiguration)
 * - generalFormConfiguration.ts (generalFormConfiguration)
 * - inhouseFormConfiguration.ts (inhouseFormConfiguration)
 * - maintenanceFormConfiguration.ts (maintenanceFormConfiguration)
 * - systemIntakeFormConfiguration.ts (systemIntakeFormConfiguration)
 */


export interface IServerActionResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface IPaginatedResult<T = unknown> extends ServerActionResult<T[]> {
  total?: number;
}


export type { Final_quality_form, Final_quality_formFormData, UpdateFinal_quality_formData } from './final_quality_formTypes';
export type { General_form, General_formFormData, UpdateGeneral_formData } from './general_formTypes';
export type { Inhouse_form, Inhouse_formFormData, UpdateInhouse_formData } from './inhouse_formTypes';
export type { Maintenance_form, Maintenance_formFormData, UpdateMaintenance_formData } from './maintenance_formTypes';
export type { System_intake_form, System_intake_formFormData, UpdateSystem_intake_formData } from './system_intake_formTypes';
