/**
 * Generated Type Definitions for GeneralForm
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface IGeneralForm {
  id: string;
  created_at: string;
  updated_at: string;
  field_technician_name: string;
  equipment_type: string;
  serial_number: string;
  support_case_number: string;
  customer_name: string;
  service_date: string;
  site_location: string;
  travel_time: number;
  mileage?: number | null;
  departure_time: string;
  arrival_time: string;
  customer_contact: string;
  contact_phone?: string | null;
  address: string;
  customer_contact_name: string;
  customer_contact_email: string;
  confirm_system_performance?: boolean;
  pre_service_ablation_performance: 'excellent' | 'good' | 'fair' | 'poor' | 'error';
  pre_service_pulsing_power: number;
  pre_service_cw_power: number;
  replace_desiccant_packs?: boolean;
  confirm_humidity_settings?: boolean;
  capture_laser_settings?: boolean;
  copy_logfiles?: boolean;
  inspect_protection_window?: boolean;
  clean_replace_optics?: boolean;
  annual_water_service?: boolean;
  confirm_o_rings_screws?: boolean;
  tape_resonator_seams?: boolean;
  inspect_protection_hose?: boolean;
  update_mds_sensor?: boolean;
  clean_equipment_dust?: boolean;
  verify_air_pressure?: boolean;
  verify_interlocks_estops?: boolean;
  work_performed: string;
  parts_used?: string | null;
  performance_test?: string | null;
  issues_found?: string | null;
  resolution_actions?: string | null;
  followup_required: 'none' | 'scheduled' | 'urgent';
  followup_notes?: string | null;
  before_service_photos: string;
  after_service_photos: string;
  customer_documents?: string | null;
  technician_signature: string;
  customer_signature: string;
  completion_date: string;
  satisfaction_rating?: '5' | '4' | '3' | '2' | '1' | null;
}

export type TGeneralFormFormData = Omit<GeneralForm, 'id' | 'created_at' | 'updated_at'>;
export type TUpdateGeneralFormData = Partial<GeneralFormFormData>;
