/**
 * Generated Type Definitions Index
 * 
 * This file is automatically generated from all FormConfiguration files.
 * Do not edit manually - regenerate using: npm run generate:all
 * 
 * Generated from 1 configuration(s):
 * - demoFormConfiguration.ts (demoFormConfiguration)
 */

// Server action result types (shared across all forms)
export interface ServerActionResult<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface PaginatedResult<T = any> extends ServerActionResult<T[]> {
  total?: number;
}

// Re-export all generated types
export type { Demo, DemoFormData, UpdateDemoData } from './demoTypes';
