/**
 * Generated Type Definitions Index
 * 
 * This file is automatically generated from all FormConfiguration files.
 * Do not edit manually - regenerate using: npm run generate:all
 * 
 * Generated from 1 configuration(s):
 * - maintenanceFormConfiguration.ts (maintenanceFormConfiguration)
 */


export interface IServerActionResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface IPaginatedResult<T = unknown> extends ServerActionResult<T[]> {
  total?: number;
}


export type { Maintenance_form, Maintenance_formFormData, UpdateMaintenance_formData } from './maintenance_formTypes';
