/**
 * Generated Type Definitions for InhouseForm
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface IInhouseForm {
  id: string;
  created_at: string;
  updated_at: string;
  service_technician: string;
  equipment_type: string;
  serial_number: string;
  work_order_number: string;
  service_type: 'repair' | 'maintenance' | 'calibration' | 'upgrade' | 'testing' | 'refurbishment' | 'other';
  service_date: string;
  customer_source?: string | null;
  priority_level: 'low' | 'normal' | 'high' | 'urgent';
  initial_condition: 'excellent' | 'good' | 'fair' | 'poor' | 'non_functional';
  initial_power_output?: number | null;
  diagnostic_tests?: boolean;
  calibration_performed?: boolean;
  software_update?: boolean;
  hardware_repair?: boolean;
  cleaning_maintenance?: boolean;
  qc_testing?: boolean;
  final_power_output?: number | null;
  final_condition: 'excellent' | 'good' | 'fair' | 'poor' | 'requires_additional_work';
  service_hours: number;
  ready_for_shipment?: boolean;
  work_description: string;
  parts_used?: string | null;
  tools_equipment_used?: string | null;
  test_results?: string | null;
  issues_encountered?: string | null;
  resolution_actions?: string | null;
  followup_required?: string | null;
  service_photos: string;
  test_documentation?: string | null;
  technician_signature: string;
  customer_signature?: string | null;
}

export type TInhouseFormFormData = Omit<InhouseForm, 'id' | 'created_at' | 'updated_at'>;
export type TUpdateInhouseFormData = Partial<InhouseFormFormData>;
