/**
 * Generated Type Definitions for SystemIntakeForm
 * 
 * This file is automatically generated from FormConfiguration.
 * Do not edit manually - regenerate using: npm run generate:all
 */

export interface ISystemIntakeForm {
  id: string;
  created_at: string;
  updated_at: string;
  receiving_technician: string;
  equipment_type: string;
  serial_number: string;
  equipment_source: 'customer_return' | 'field_service' | 'rental_return' | 'demo_return' | 'manufacturing' | 'other';
  source_contact: string;
  intake_date: string;
  rma_case_number?: string | null;
  transport_method: 'ups' | 'fedex' | 'freight' | 'customer_delivery' | 'field_tech' | 'other';
  physical_condition: 'excellent' | 'good' | 'fair' | 'poor' | 'damaged';
  power_on_test: 'pass' | 'fail' | 'partial' | 'not_tested';
  laser_performance?: 'excellent' | 'good' | 'fair' | 'poor' | 'not_functional' | 'not_tested' | null;
  power_output?: number | null;
  accessories_included?: boolean;
  documentation_included?: boolean;
  software_included?: boolean;
  packaging_condition: 'excellent' | 'good' | 'fair' | 'poor' | 'damaged';
  reported_issues?: string | null;
  visual_inspection_notes?: string | null;
  immediate_action_required?: string | null;
  equipment_photos: string;
  supporting_documents?: string | null;
  technician_signature: string;
  supervisor_signature?: string | null;
}

export type TSystemIntakeFormFormData = Omit<SystemIntakeForm, 'id' | 'created_at' | 'updated_at'>;
export type TUpdateSystemIntakeFormData = Partial<SystemIntakeFormFormData>;
