import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Toaster } from 'sonner';
import { ThemeProvider } from 'next-themes';
import ThemeSwitch from '@/components/ThemeSwitcher';
import { PlusIcon } from '@radix-ui/react-icons';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Header */}
          <header className='border-border bg-card border-b'>
            <div className='container mx-auto px-4 py-6'>
              <div className='flex items-center justify-between'>
                <div>
                  <h1 className='text-foreground text-3xl font-bold'>
                    formscaffold.io
                  </h1>
                  <p className='text-muted-foreground mt-1'>
                    Generate full-stack forms with TypeScript, React Hook Form,
                    Zod validation, and PostgreSQL
                  </p>
                </div>
                <div className='flex gap-2'>
                  <Link
                    href='/create'
                    className='bg-primary text-primary-foreground hover:bg-primary/90 inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors'
                  >
                    <PlusIcon className='h-4 w-4' />
                    New Form
                  </Link>
                  <ThemeSwitch />
                </div>
              </div>
            </div>
          </header>
          {children}
          <Toaster closeButton={true} expand={true} richColors={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
