import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Toaster } from 'sonner';
import { ThemeProvider } from 'next-themes';
import ThemeSwitch from '@/components/ThemeSwitcher';
import { PlusCircledIcon, PlusIcon } from '@radix-ui/react-icons';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Header */}
          <header className='border-border bg-card border-b'>
            <div className='flex flex-row items-center justify-between p-2 md:p-10'>
              <div>
                <h1 className='text-foreground text-3xl font-bold'>
                  formscaffold.io
                </h1>
                <p className='text-muted-foreground mt-1 hidden md:flex'>
                  Generate full-stack forms with TypeScript, React Hook Form,
                  Zod validation, and PostgreSQL
                </p>
              </div>
              <div className='flex w-[50%] flex-row flex-nowrap items-end justify-end gap-5'>
                <ThemeSwitch
                  className={`flex text-xs md:text-base lg:text-xl`}
                />
                <Link
                  href='/create'
                  className='bg-primary text-primary-foreground hover:bg-primary/90 flex items-center gap-2 px-4 py-2 text-sm font-medium transition-colors md:text-xl'
                >
                  <PlusCircledIcon className='h-8 w-8' />
                  New Form
                </Link>
              </div>
            </div>
          </header>
          {children}
          <Toaster closeButton={true} expand={true} richColors={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
