import { IFormConfiguration } from '@/types/globalFormTypes';

export const sampleConfigurations = {
  basic: {
    title: 'Basic Contact Form',
    description: 'A simple contact form with basic fields',
    postgresTableName: 'contact_form',
    submitButtonText: 'Send Message',
    resetButtonText: 'Clear Form',
    showResetButton: true,
    sections: [
      {
        title: 'Contact Information',
        description: 'Please provide your contact details',
        gridCols: '2' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'First Name',
            name: 'first_name',
            type: 'text' as const,
            required: true,
            placeholder: 'Enter your first name',
            default: '',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 100,
            },
          },
          {
            label: 'Last Name',
            name: 'last_name',
            type: 'text' as const,
            required: true,
            placeholder: 'Enter your last name',
            default: '',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 100,
            },
          },
          {
            label: 'Email',
            name: 'email',
            type: 'email' as const,
            required: true,
            placeholder: 'your.email@example.com',
            default: '',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 255,
            },
          },
          {
            label: 'Phone',
            name: 'phone',
            type: 'tel' as const,
            required: false,
            placeholder: '(555) 123-4567',
            default: '',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 20,
            },
          },
        ],
      },
      {
        title: 'Message',
        description: 'What would you like to tell us?',
        gridCols: '1' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Subject',
            name: 'subject',
            type: 'select' as const,
            required: true,
            options: [
              { value: 'general', label: 'General Inquiry' },
              { value: 'support', label: 'Technical Support' },
              { value: 'sales', label: 'Sales Question' },
              { value: 'feedback', label: 'Feedback' },
            ],
            default: '',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 50,
            },
          },
          {
            label: 'Message',
            name: 'message',
            type: 'textarea' as const,
            required: true,
            placeholder: 'Please enter your message here...',
            rows: 5,
            default: '',
            pgConfig: {
              type: 'TEXT' as const,
            },
          },
          {
            label: 'Priority',
            name: 'priority',
            type: 'radio' as const,
            required: false,
            options: [
              { value: 'low', label: 'Low' },
              { value: 'medium', label: 'Medium' },
              { value: 'high', label: 'High' },
            ],
            default: 'medium',
            pgConfig: {
              type: 'VARCHAR' as const,
              length: 20,
            },
          },
          {
            label: 'Subscribe to Newsletter',
            name: 'newsletter',
            type: 'checkbox' as const,
            required: false,
            description: 'Receive updates and news from us',
            default: false,
            pgConfig: {
              type: 'BOOLEAN' as const,
            },
          },
        ],
      },
    ],
  } as IFormConfiguration,

  comprehensive: {
    title: 'Comprehensive Demo Form',
    description: 'A demonstration form showcasing all available field types',
    postgresTableName: 'demo_comprehensive',
    submitButtonText: 'Submit Demo',
    saveDraftButtonText: 'Save Draft',
    showDraftButton: true,
    resetButtonText: 'Reset Form',
    showResetButton: true,
    sections: [
      {
        title: 'Text Inputs',
        description: 'Various text input types',
        gridCols: '2' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Text Field',
            name: 'text_field',
            type: 'text' as const,
            required: true,
            placeholder: 'Enter some text',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 255 },
          },
          {
            label: 'Email Address',
            name: 'email_field',
            type: 'email' as const,
            required: true,
            placeholder: 'user@example.com',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 255 },
          },
          {
            label: 'Password',
            name: 'password_field',
            type: 'password' as const,
            required: false,
            placeholder: 'Enter password',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 255 },
          },
          {
            label: 'Website URL',
            name: 'url_field',
            type: 'url' as const,
            required: false,
            placeholder: 'https://example.com',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 500 },
          },
          {
            label: 'Phone Number',
            name: 'tel_field',
            type: 'tel' as const,
            required: false,
            placeholder: '(555) 123-4567',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 20 },
          },
          {
            label: 'Search Query',
            name: 'search_field',
            type: 'search' as const,
            required: false,
            placeholder: 'Search...',
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 255 },
          },
        ],
      },
      {
        title: 'Numeric & Range Inputs',
        description: 'Number, range, and related inputs',
        gridCols: '2' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Age',
            name: 'number_field',
            type: 'number' as const,
            required: false,
            placeholder: 'Enter your age',
            min: 0,
            max: 120,
            default: 0,
            pgConfig: { type: 'INTEGER' as const },
          },
          {
            label: 'Experience Level',
            name: 'range_field',
            type: 'range' as const,
            required: false,
            min: 0,
            max: 10,
            step: '1',
            default: 5,
            pgConfig: { type: 'INTEGER' as const },
          },
        ],
      },
      {
        title: 'Date & Time Inputs',
        description: 'Various date and time field types',
        gridCols: '2' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Birth Date',
            name: 'date_field',
            type: 'date' as const,
            required: false,
            default: '',
            pgConfig: { type: 'DATE' as const },
          },
          {
            label: 'Appointment Time',
            name: 'time_field',
            type: 'time' as const,
            required: false,
            default: '',
            pgConfig: { type: 'TIME' as const },
          },
          {
            label: 'Event DateTime',
            name: 'datetime_field',
            type: 'datetime-local' as const,
            required: false,
            default: '',
            pgConfig: { type: 'TIMESTAMP' as const },
          },
          {
            label: 'Birth Month',
            name: 'month_field',
            type: 'month' as const,
            required: false,
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 7 },
          },
          {
            label: 'Work Week',
            name: 'week_field',
            type: 'week' as const,
            required: false,
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 8 },
          },
        ],
      },
      {
        title: 'Selection Inputs',
        description: 'Dropdowns, radio buttons, and checkboxes',
        gridCols: '1' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Country',
            name: 'select_field',
            type: 'select' as const,
            required: false,
            options: [
              { value: 'us', label: 'United States' },
              { value: 'ca', label: 'Canada' },
              { value: 'uk', label: 'United Kingdom' },
              { value: 'au', label: 'Australia' },
            ],
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 10 },
          },
          {
            label: 'Preferred Contact Method',
            name: 'radio_field',
            type: 'radio' as const,
            required: false,
            options: [
              { value: 'email', label: 'Email' },
              { value: 'phone', label: 'Phone' },
              { value: 'sms', label: 'SMS' },
            ],
            default: 'email',
            pgConfig: { type: 'VARCHAR' as const, length: 20 },
          },
          {
            label: 'Terms and Conditions',
            name: 'checkbox_field',
            type: 'checkbox' as const,
            required: true,
            description: 'I agree to the terms and conditions',
            default: false,
            pgConfig: { type: 'BOOLEAN' as const },
          },
          {
            label: 'Enable Notifications',
            name: 'toggle_field',
            type: 'toggle' as const,
            required: false,
            description: 'Receive push notifications',
            default: true,
            pgConfig: { type: 'BOOLEAN' as const },
          },
        ],
      },
      {
        title: 'Visual & File Inputs',
        description: 'Color pickers, file uploads, and visual elements',
        gridCols: '2' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Favorite Color',
            name: 'color_field',
            type: 'color' as const,
            required: false,
            default: '#3b82f6',
            pgConfig: { type: 'VARCHAR' as const, length: 7 },
          },
          {
            label: 'Profile Picture',
            name: 'file_field',
            type: 'file' as const,
            required: false,
            accept: 'image/*',
            multiple: false,
            default: [],
            pgConfig: { type: 'TEXT' as const },
          },
          {
            label: 'Documents',
            name: 'files_field',
            type: 'file' as const,
            required: false,
            accept: '.pdf,.doc,.docx',
            multiple: true,
            default: [],
            pgConfig: { type: 'TEXT' as const },
          },
        ],
      },
      {
        title: 'Advanced Fields',
        description: 'Textarea and other advanced input types',
        gridCols: '1' as const,
        spacing: 'md' as const,
        fields: [
          {
            label: 'Comments',
            name: 'textarea_field',
            type: 'textarea' as const,
            required: false,
            placeholder: 'Enter your comments here...',
            rows: 4,
            default: '',
            pgConfig: { type: 'TEXT' as const },
          },
          {
            label: 'Digital Signature',
            name: 'signature_field',
            type: 'signature' as const,
            required: false,
            description: 'Please provide your digital signature',
            default: '',
            pgConfig: { type: 'TEXT' as const },
          },
          {
            label: 'User ID',
            name: 'hidden_field',
            type: 'hidden' as const,
            required: false,
            default: 'auto-generated-id',
            pgConfig: { type: 'VARCHAR' as const, length: 50 },
          },
        ],
      },
    ],
  } as IFormConfiguration,

  minimal: {
    title: 'Minimal Form',
    description: 'A simple form with just the essentials',
    postgresTableName: 'minimal_form',
    sections: [
      {
        title: 'Basic Info',
        fields: [
          {
            label: 'Name',
            name: 'name',
            type: 'text' as const,
            required: true,
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 100 },
          },
          {
            label: 'Email',
            name: 'email',
            type: 'email' as const,
            required: true,
            default: '',
            pgConfig: { type: 'VARCHAR' as const, length: 255 },
          },
        ],
      },
    ],
  } as IFormConfiguration,
};

export function getSampleConfigurationJson(
  type: keyof typeof sampleConfigurations,
): string {
  return JSON.stringify(sampleConfigurations[type], null, 2);
}

export function getAllSampleTypes(): Array<{
  key: keyof typeof sampleConfigurations;
  title: string;
  description: string;
}> {
  return [
    {
      key: 'basic',
      title: 'Basic Contact Form',
      description: 'A standard contact form with essential fields',
    },
    {
      key: 'comprehensive',
      title: 'Comprehensive Demo',
      description: 'Showcases all available field types',
    },
    {
      key: 'minimal',
      title: 'Minimal Form',
      description: 'Simplest possible form structure',
    },
  ];
}
