import { z } from 'zod';

/**
 * Generated Zod Schema for Demo
 * 
 * This file is automatically generated from FormConfiguration.
 * Import and use this schema for validation in your application.
 */

// Form validation schema (excludes database-generated fields)
export const demoSchema = z.object({
  full_name: z.string(),
  email: z.string(),
  website: z.string().optional(),
  phone: z.string().optional(),
  keywords: z.string().optional(),
  secret_code: z.string().optional(),
  age: z.number(),
  salary: z.number().optional(),
  experience_level: z.string().optional(),
  satisfaction: z.string().optional(),
  birth_date: z.date().optional(),
  appointment_time: z.string().optional(),
  event_datetime: z.string().optional(),
  target_month: z.string().optional(),
  target_week: z.string().optional(),
  language: z.string(),
  skill_level: z.string(),
  newsletter_subscription: z.boolean().optional(),
  notifications_enabled: z.string().optional(),
  favorite_color: z.string().optional(),
  profile_picture: z.string().optional(),
  resume_file: z.string().optional(),
  biography: z.string().optional(),
  config_json: z.string().optional(),
  skills: z.string().optional(),
  user_id: z.string().optional(),
  metadata: z.string().optional(),
});

// Complete schema including database fields (for type generation)
export const completeDemoSchema = z.object({
  id: z.string().uuid(),
  created_at: z.date(),
  updated_at: z.date(),
  full_name: z.string(),
  email: z.string(),
  website: z.string().optional(),
  phone: z.string().optional(),
  keywords: z.string().optional(),
  secret_code: z.string().optional(),
  age: z.number(),
  salary: z.number().optional(),
  experience_level: z.string().optional(),
  satisfaction: z.string().optional(),
  birth_date: z.date().optional(),
  appointment_time: z.string().optional(),
  event_datetime: z.string().optional(),
  target_month: z.string().optional(),
  target_week: z.string().optional(),
  language: z.string(),
  skill_level: z.string(),
  newsletter_subscription: z.boolean().optional(),
  notifications_enabled: z.string().optional(),
  favorite_color: z.string().optional(),
  profile_picture: z.string().optional(),
  resume_file: z.string().optional(),
  biography: z.string().optional(),
  config_json: z.string().optional(),
  skills: z.string().optional(),
  user_id: z.string().optional(),
  metadata: z.string().optional(),
});

export type DemoFormData = z.infer<typeof demoSchema>;
export type CompleteDemo = z.infer<typeof completeDemoSchema>;
